### ISSUE TITLE
Review Terraform Module Standards

### ISSUE THREAD

**Issue by bellanov** [bellanov/terraform-aws-storage#1]
In order to publish Terraform modules to the public registry, they need to adhere to a certain format and set of rules.

**Standard Module Structure**

https://developer.hashicorp.com/terraform/language/modules/develop/structure

**Tasks**

- Review the resource above
- Create a branch from this issue
- Create blank **main.tf**, **variables.tf**, and **outputs.tf** files.

**Comment by prattsvee** [comment]
Added files main , variables output , understood the standards , format as mentioned in the Terraform documentation too. 
The branch created is called AWS_dev and can be merged to main after PR are reviewed.

**Comment by bellanov** [comment]
Yea, you did this completely wrong lol. Reopening and let's do this together.

**Comment by bellanov** [comment]
Pardon the harsh words. I just noticed. 

Did not mean to come off that way.

**Comment by prattsvee** [comment]
it is okay , I just created these files on the branch connected to this issue so I think this should be okay .  I have a PR ready for it .

**Comment by bellanov** [comment]
Yep, well done. Fell free to open the Pull Request and we can close this out.

**Comment by bellanov** [comment]
I shouldn't be opening these for you lol. Moving on...

![Image](https://github.com/user-attachments/assets/4d57c37d-601c-4309-b0a6-560c061cfae3)
